### ISSUE TITLE
'clear' function should be void

### ISSUE THREAD

**Issue by tudortimi-ifx** [nosnhojn/svmock#1]
In '__mocker', the 'clear()' functions should be declared as 'virtual function void clear()', otherwise it defaults to returning 'int' (I think?).

Also, in the definition of `SVMOCK(...), the 'clear()' function is explicitly declared to return bit, but no result is returned.

Due to the issues mentioned above I got compiler errors when requiring return values be used (in IUS, '-ncerror FUNTSK').

**Comment by nosnhojn** [comment]
fixed in https://github.com/nosnhojn/svmock/commit/6f926fecfbc9607c5dc0d44c75ce3b8c567a3523
