### ISSUE TITLE
Release 0.1 is a moving target

### ISSUE THREAD

**Issue by bentitmus** [nosnhojn/svmock#12]
The [AgileSoC website](http://agilesoc.com/2018/07/11/svmock-version-0-1/) announcing SVMock version 0.1 has a download link to a zip of master on GitHub. This is a moving target as you make changes. Would it be possible to create a release in GitHub so that there is a fixed known version of the project? It would be useful to have a release (0.2?) that includes the name change from check to verify (so I can convince my IT department to install an updated version!).

**Comment by nosnhojn** [comment]
this is a dumb question, but I'm assuming your IT folks would go to the release page and grab the 1 they want? if yes then I think I got it sorted out. I added a release script that I'll use to tag new versions. that's accessible from: https://github.com/nosnhojn/svmock/releases

**Comment by bentitmus** [comment]
Thanks. This is exactly what I needed!
