### ISSUE TITLE
Actual values captured for method arguments should be cleared when 'clear()' is called

### ISSUE THREAD

**Issue by tudortimi-ifx** [nosnhojn/svmock#7]
Actual values for arguments aren't cleared, which leads to tests that pass when they should fail:

// mock cleared in 'setup()'

`SVTEST(...)
uut.do_stuff(); // calls mock.some_func("foo");
`SVTEST_END

`SVTEST(...)
`EXPECT_CALL(mock, some_func).with_args("foo");
uut.do_other_stuff(); // doesn't call 'some_func()' on mock
`SVTEST_END

Second test is pass because in the first test 'withAct' was set to "foo".

**Comment by nosnhojn** [comment]
this is a prickly one! I'll need to re-structure how this is done so I can avoid knowing what the data types are.

**Comment by tudortimi-ifx** [comment]
You don't need to, it's possible to get the default by using a dummy variable:

function clear();
  // ...
  T default_val;
  withAct_0 = default_val;
endfunction

One corner case might be when expecting the default values, but the function isn't called at all. In GoogleMock, an expectation like this would also increment the expected call counter, so the case of the function not getting called at all would be flagged as an error.

**Comment by nosnhojn** [comment]
try it now. close if you're good with it. I put the exp and act in a container class of their own. then I create a new instance of it in clear. pretty much what you suggested, just slightly different.

**Comment by nosnhojn** [comment]
expectations are cleared on 'clear()'. 'clear()' can be called by users. it's also called with 'check()'.
