### ISSUE TITLE
output/ref/inout arguments break everything

### ISSUE THREAD

**Issue by nosnhojn** [nosnhojn/svmock#8]
output/ref/inout arguments break everything. I can't handle them as part of the type input to the mock function/task macros so I need new macro arguments where people specify output/ref/inout for each function/task argument

example. current task macro with 1 argument is this...

`define SVMOCK_TASK1(NAME,TYPE0,ARG0,MOD0)

it'll need to get updated to this (i.e. DIR0 is new)...

`define SVMOCK_TASK1(NAME,DIR0,TYPE0,ARG0,MOD0)

**Comment by nosnhojn** [comment]
default arg values also break everything so I need to add those as well.

`define SVMOCK_TASK1(NAME,DIR0,TYPE0,ARG0,MOD0,DEF0)

**Comment by tudortimi-ifx** [comment]
On this note, I noticed that function default arguments can also cause issues. In IUS I get a warning stating that the default argument of a function is not the same as in the base class. They also state that this will be an error in the future. This means that this information also has to be transported to the mock macros. (I can also imagine that this might be impossible to do without requiring the user to do something like `SVMOCK_FUNCTION1(some_func, some_return_type, some_arg, input, some_input_type, <arrayness>, = some_default_value) - note the '=' in the macro arg.)

**Comment by nosnhojn** [comment]
agree on the usability aspect. I'm playing around with format now to see if there's a happy medium.

**Comment by nosnhojn** [comment]
this is where I'm at. not super pretty but I found comments adequate for maintaining argument order. if you want to take a look, it's working on 'git checkout -b add_dir_to_macro'. I'll take a few days to pondering yet to see if I can come up with something better. if not, I'll merge it next week to master.

```
SVMOCK_VFUNC3(functionDynamicArrayArgReturnVoid, /*input*/, string,  x, /*scalar*/, /*no-default*/,
                                                 /*input*/, objtype, y, [],         /*no-default*/,
                                                 /*input*/, int,     z, /*scalar*/, /*no-default*/)
```

**Comment by nosnhojn** [comment]
released on master with updated user guide.
